version: '3.9'
services:
  # Сервис для разворачивания контейнера с базой данных
  database:
    image: postgres:latest
    hostname: database
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=animal-chipization
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  # Сервис для разворачивания контейнера с приложением
  webapi:
    build:
      dockerfile: Dockerfile
      context: .
    hostname: webapi
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/animal-chipization
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: curl http://localhost:8080 || exit 0
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 10s
    # Сервис для разворачивания контейнера с автотестами
  tests:
    image: mrexpen/planet_olymp_phase2
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
        webapi:
          condition: service_healthy
    environment:
      SERVER_URL: http://webapi:8080
      STAGE: 0