CREATE TYPE GENDER AS ENUM
    ('MALE', 'FEMALE', 'OTHER');
CREATE TYPE LIFE_STATUS AS ENUM
    ('ALIVE', 'DEAD');

CREATE TABLE account
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL primary key,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255) unique
);

CREATE TABLE location_point
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL primary key,
    latitude  DOUBLE PRECISION                        NOT NULL,
    longitude DOUBLE PRECISION                        NOT NULL
);

CREATE TABLE animal_type
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL primary key,
    type VARCHAR(255)
);

CREATE TABLE animal
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL primary key,
    weight               FLOAT                                   NOT NULL,
    length               FLOAT                                   NOT NULL,
    height               FLOAT                                   NOT NULL,
    gender               GENDER,
    life_status          VARCHAR(255),
    chipping_date_time   TIMESTAMP WITHOUT TIME ZONE,
    chipper_id           BIGINT,
    chipping_location_id BIGINT,
    death_date_time      TIMESTAMP WITHOUT TIME ZONE default null,
    foreign key (chipper_id) references account (id),
    foreign key (chipping_location_id) references location_point (id)
);

--
-- CREATE TABLE if not exists account_chipped_animals
-- (
--     account_id         BIGINT NOT NULL,
--     chipped_animals_id BIGINT NOT NULL primary key,
--     foreign key (account_id) references account (id),
--     foreign key (chipped_animals_id) references animal (id)
-- );

CREATE TABLE animal_visited_locations
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL primary key,
    animal_id         BIGINT                                  NOT NULL,
    location_point_id BIGINT                                  NOT NULL,
    date_time_of_visit_location_point TIMESTAMP WITHOUT TIME ZONE,
    foreign key (animal_id) references animal (id),
    foreign key (location_point_id) references location_point (id)
);

CREATE TABLE animal_animal_type
(
    animal_id      BIGINT NOT NULL,
    animal_type_id BIGINT NOT NULL,
    primary key (animal_id, animal_type_id),
    foreign key (animal_id) references animal (id),
    foreign key (animal_type_id) references animal_type (id)
);